const routerHandleResult = {
  NO_URL_PATH_MATCH: 'NO_URL_PATH_MATCH',
  NO_HTTP_METHOD_MATCH: 'NO_HTTP_METHOD_MATCH',
  HANDLED: 'HANDLED',
  ID_NOT_FOUND: 'CUSTOMER ID NOT FOUND',
  SERVER_REQUEST_ERROR: 'REQUEST TO SERVER IS INCORRECT OR CORRUPT'
};

module.exports = { routerHandleResult };
