const routerHandleResult = {
  NO_URL_PATH_MATCH: 'NO_URL_PATH_MATCH',
  NO_HTTP_METHOD_MATCH: 'NO_HTTP_METHOD_MATCH',
  ID_NOT_FOUND: 'CUSTOMER ID NOT FOUND',
  REQUEST_ERROR: 'REQUEST TO SERVER IS INCORRECT OR CORRUPT',
  HANDLED: 'HANDLED',
};

module.exports = { routerHandleResult };
